DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_user WHERE usename = 'root') THEN
    CREATE USER erp WITH PASSWORD 'root123';
  END IF;
END
$$;

SELECT 'CREATE DATABASE erp' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'erp');

GRANT ALL PRIVILEGES ON DATABASE erp TO erp;